services:
  phpfpm:
    image: itkdev/php8.3-fpm:latest
    user: ${COMPOSE_USER:-deploy}
    profiles:
      - dev
    volumes:
      - .:/app
    environment:
      PHP_MEMORY_LIMIT: 512M
      COMPOSER_MEMORY_LIMIT: -1

  # Code checks tools
  markdownlint:
    image: itkdev/markdownlint
    profiles:
      - dev
    volumes:
      - ./:/md

  prettier:
    # Prettier does not (yet, fcf.
    # https://github.com/prettier/prettier/issues/15206) have an official
    # docker image.
    # https://hub.docker.com/r/jauderho/prettier is good candidate (cf. https://hub.docker.com/search?q=prettier&sort=updated_at&order=desc)
    image: jauderho/prettier
    profiles:
      - dev
    volumes:
      - ./:/work
