# https://taskfile.dev

version: "3"

tasks:
  generate:
    desc: Generate stuff …
    cmds:
      - task: compose
        vars:
          COMPOSE_ARGS: run --rm phpfpm composer install
      - task: compose
        vars:
          COMPOSE_ARGS: run --rm phpfpm bin/generate resources
      - task: compose
        vars:
          COMPOSE_ARGS: run --rm phpfpm bin/generate classes

  compose:
    cmds:
      - docker compose {{.COMPOSE_ARGS}} {{.CLI_ARGS}}
    internal: true
