# https://taskfile.dev

version: "3"

tasks:
  generate:
    desc: Generate stuff …
    cmds:
      - task: compose
        vars:
          COMPOSE_ARGS: run --rm phpfpm composer install
      - task: compose
        vars:
          COMPOSE_ARGS: run --rm phpfpm bin/generate resources
      - task: compose
        vars:
          COMPOSE_ARGS: run --rm phpfpm bin/generate classes

  compose:
    cmds:
      - docker compose {{.COMPOSE_ARGS}} {{.CLI_ARGS}}
    internal: true

  composer:
    desc: Run composer inside docker compose setup, e.g. `task {{.TASK}} -- install`
    cmds:
      - task: compose
        vars:
          COMPOSE_ARGS: run --rm phpfpm composer

  php:
    # https://taskfile.dev/docs/reference/templating#task-1
    desc: Run PHP inside docker compose setup, e.g. `task {{.TASK}} -- bin/serviceplatformen-sf2900-fordelingsobjekt-list`
    cmds:
      - task: compose
        vars:
          COMPOSE_ARGS: run --rm phpfpm php

  debug:php:
    desc: Run PHP inside docker compose setup with Xdebug enabled, e.g. `task {{.TASK}} -- bin/serviceplatformen-sf2900-fordelingsobjekt-list`
    cmds:
      - task: compose
        vars:
          COMPOSE_ARGS: run --env PHP_XDEBUG_MODE=debug --env PHP_XDEBUG_WITH_REQUEST=yes --rm phpfpm php

  default:
    cmds:
      - task --list
    silent: true
